=begin
#Demo Client for Passmeister Apple Wallet and Google Wallet API

#[www.passmeister.com](https://www.passmeister.com).

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

module SwaggerClient
  VERSION = '1.0.0'
end
